# Generated by Django 5.0.2 on 2024-02-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='member',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
