# Generated by Django 5.0.2 on 2024-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0002_alter_spot_member_alter_spot_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='member',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
