# Generated by Django 5.0.2 on 2024-03-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0002_remove_post_location_post_city_post_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='member',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='spot.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='members',
            field=models.ManyToManyField(blank=True, to='spot.member'),
        ),
    ]
