# Generated by Django 5.0.2 on 2024-03-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_remove_post_category_remove_post_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='map_link',
            field=models.TextField(null=True),
        ),
    ]
