# Generated by Django 5.0.2 on 2024-03-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_alter_post_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='map_link',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
